#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import os

# Set the proxy server if necessary 
os.environ['HTTP_PROXY']='<proxy>'
os.environ['HTTPS_PROXY']='<proxy>'

url = 'https://api.github.com/search/repositories?q=language:python&sort=stars'

# Now we have a Response object called r. We can get all the information from this object.
r = requests.get(url)

# Status code: 200
# This means the request was successful
print("Status code:", r.status_code)

# There's also a builtin JSON decoder.
# The API returns the information in JSON format.
response_dict = r.json()

# {'total_count': 2569025, 'incomplete_results': False, 'items': [{'id': 21289110, 'name': 'awesome-python', 'full_name': 'vinta/awesome-python', ther_user}', ...}]}
print(response_dict)

# dict_keys(['total_count', 'incomplete_results', 'items'])
print(response_dict.keys())

# Total repositories: 2569027
print("Total repositories:", response_dict['total_count'])

repo_dicts = response_dict['items']

# Repositories returned: 30
print("Repositories returned:", len(repo_dicts))

# Return the first repository information
# Keys: 72
# archive_url
# archived
# assignees_url
# blobs_url
# branches_url
# clone_url
# collaborators_url

repo_dict = repo_dicts[0]
print("\nKeys:", len(repo_dict))
for key in sorted(repo_dict.keys()):
    print(key)

# Selected information about first repository:
# Name: awesome-python
# Owner: vinta
# Stars: 48828
# Repository: https://github.com/vinta/awesome-python
# Created: 2014-06-27T21:00:06Z
# Updated: 2018-04-23T04:57:54Z
# Description: A curated list of awesome Python frameworks, libraries, software and resources
print("\nSelected information about first repository:")
print('Name:', repo_dict['name'])
print('Owner:', repo_dict['owner']['login'])
print('Stars:', repo_dict['stargazers_count'])
print('Repository:', repo_dict['html_url'])
print('Created:', repo_dict['created_at'])
print('Updated:', repo_dict['updated_at'])
print('Description:', repo_dict['description'])

print("\nSelected information about each repository:")
for repo_dict in repo_dicts:
    print('\nName:', repo_dict['name'])
    print('Owner:', repo_dict['owner']['login'])
    print('Stars:', repo_dict['stargazers_count'])
    print('Repository:', repo_dict['html_url'])
    print('Description:', repo_dict['description'])
